### ISSUE TITLE
Any help on a dependencies issue, please..?

### ISSUE THREAD

**Issue by Txellenne** [versoft/mokio#4]
Hi, I'm trying to install `mokio` following guidelines posted [here](http://www.mokio.org/support) but unsuccessful. The `new_app` got created (it seems OK) but got into a dependencies conflict after adding, as instructed, `gem 'mokio'` in the `gemfile`. I also tried `$ bundle update` as the output itself suggests but not success. 
I'd appreciate any help.
```bash
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "jquery-rails":
  In snapshot (Gemfile.lock):
    jquery-rails (= 4.2.2)

  In Gemfile:
    jquery-rails

    mokio was resolved to 0.0.5, which depends on
      jquery-rails (>= 3.1.0, ~> 3.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by tomasz-krol** [comment]
Hi, 
sure I'll try to help. First of all, which version of Rails do you want to use? I see that bundle resolves mokio to `0.0.5` which is very old. Currently on rubygems there is `0.0.14` version compatible with Rails `4.1.1` and Ruby `2.1.2`, so first maybe try set in your `Gemfile` the latest version of Mokio. However you can also use Mokio with brand new Rails 5. Take a look into this branch `rails5.0`. You can use it in your `Gemfile` as following:
`gem "mokio", '0.0.14',:github => 'versoft/mokio', :branch => 'rails5.0'`
But there are some issues with that vesion. On the day this branch was released, there wasn't proper version of `simple_form` gem, so we're using this gem instead:
`gem 'simple_form', github: 'kesha-antonov/simple_form', branch: 'rails-5-0'`, but I think that original `simple_form` is now compatible with Rails 5, so check it out.

Second issue is about no longer supported gem `youtube_it`. We also use some fork to get mokio work:
`gem 'youtube_it', github: 'LiveWorld/youtube_it'`

I hope that above informations will help you.

Take care!

**Comment by Txellenne** [comment]
Hi, thanks. 
I tried the option `gem "mokio", '0.0.14',:github => 'versoft/mokio', :branch => 'rails5.0'` and after sorting out some, fortunately,  no difficult to resolve dependence issues (like installing `rmagick`) the output I got when run the command `rake mokio:install` is shown below:   

```
$ rake mokio:install
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 10.5.0. 
```

**Comment by tomasz-krol** [comment]
Hi,

The `bundle install` performs ok? Maybe try `bundle exec rake mokio:install` or remove all versions of `rake` from your gemset and run `bundle install` again.
